### ISSUE TITLE
'free-hosting.php' doesn't exist..

### ISSUE THREAD

**Issue by CookieGuy123** [MOFHDevs/mofh-material-template#11]
**I love this template, but when I click on the 'Free Hosting' tab it says free-hosting.php doesn't exist.**
And that means that if I use this template then people can't register to my hosting...
please fix this (add the free-hosting.php or something) :)

**Comment by 4yx** [comment]
I'll try my best to. I was supposed to add it, but certain events have prevented me from being able to work on it so far. I'm very busy until Tuesday/Thursday, but after that I will try to finish it and add it to the project.

Thanks for your kind words, and for your patience.

**Comment by 4yx** [comment]
Thank you for your patience with me as I was doing this. The free hosting page is now ready.
More changes are coming soon, if you'd like to track development you can check [v2](https://github.com/MOFHDevs/mofh-material-template/tree/v2).
